Refactor k3 to k6
mirror-media/InstantCoffee pull request #269
Opened 2023-08-21 06:47 UTC by MikeMirrorMedia

將App資料來源從k3轉至k6

2023-08-31 10:59 UTC, erase2004 requested changes
* 個人頁面 > 訂閱新聞類別的變動與下面的訂閱的文章清單沒有連動
* 影音頁下拉，載入更多的清單是有問題的 (那邊有觀測到持續呼叫同樣的 URL，沒有呼叫 next page)

2023-08-31 10:59 UTC, erase2004 commented on lib/configs/baseConfig.dart
> +  String get graphqlRoot;
同 https://github.com/mirror-media/apps-configs/pull/3#discussion_r1301369391

2023-08-31 10:59 UTC, erase2004 commented on lib/pages/storyPage/news/story_widget.dart
> +            story.publishedDate,
這裡需要用 臺北時間

2023-08-31 10:59 UTC, erase2004 commented on lib/pages/storyPage/news/story_widget.dart
> +          story.updatedAt,
這裡需要用 臺北時間

2023-09-01 02:49 UTC, MikeMirrorMedia commented on pubspec.yaml
> -    - assets/image/subscription_icon.png
done

2023-09-01 02:50 UTC, MikeMirrorMedia commented on pubspec.yaml
目前
environment:
  sdk: '>=2.12.0 <3.0.0'
有包含 2.19

2023-09-01 02:54 UTC, MikeMirrorMedia commented on lib/models/story.dart
> +      photoUrl = json['heroImage']['resized']['original'];
done

2023-09-01 02:54 UTC, MikeMirrorMedia commented on lib/models/record.dart
> +      photoUrl = json['heroImage']['resized']['original'];
done

2023-09-01 02:55 UTC, MikeMirrorMedia commented on lib/services/category_service.dart
remove

2023-09-01 03:02 UTC, MikeMirrorMedia commented on lib/pages/top_list_page/topic_list_controller.dart
> +  void fetchMoreTopics() async {
done

2023-09-01 03:04 UTC, MikeMirrorMedia commented on lib/pages/top_list_page/topic_list_controller.dart
> +  late TopicRepos repository;
done

2023-09-01 03:04 UTC, MikeMirrorMedia commented on lib/pages/top_list_page/topic_list_controller.dart
> +  final topicList = <Topic>[].obs;
done

2023-09-01 03:04 UTC, MikeMirrorMedia commented on lib/pages/top_list_page/topic_list_controller.dart
> +    displayToast(loadSuccessful.format([newTopicList.length]));
done

2023-09-01 03:05 UTC, MikeMirrorMedia commented on lib/pages/top_list_page/topic_list_page.dart
> +        title: const Text('Topic List'),
done

2023-09-01 03:07 UTC, MikeMirrorMedia commented on lib/blocs/storyPage/news/bloc.dart
這部分移除 會動到部分邏輯 歸到GetX架構調整

2023-09-01 03:07 UTC, MikeMirrorMedia commented on lib/pages/storyPage/news/story_widget.dart
> +            story.publishedDate,
done

2023-09-01 03:07 UTC, MikeMirrorMedia commented on lib/pages/storyPage/news/story_widget.dart
> +          story.updatedAt,
done

2023-09-04 03:42 UTC, MikeMirrorMedia commented on lib/configs/baseConfig.dart
> +  String get graphqlRoot;
done

2023-09-04 03:42 UTC, MikeMirrorMedia commented on lib/blocs/personalPage/category/bloc.dart
> +      List<Category>? localCategoryList =
done

2023-09-04 08:34 UTC, erase2004 requested changes
待解決的問題：
1. https://github.com/mirror-media/apps-configs/pull/3#issuecomment-1704811823
2. 個人頁面，訂閱的類別顯示應該要是名稱，而不是 slug
<img width="315" alt="Snipaste_2023-09-04_16-29-20" src="https://github.com/mirror-media/InstantCoffee/assets/1367757/08e30cfd-9820-4e31-9ece-eed4d908f76e">

3. 個人頁面，訂閱的類別，在使用者 localstorage 有資料的情況下，新舊資料不相容，導致出錯 (app 重裝雖然可以解決問題，但是不適合作為提供給使用者的方法)
4. 影音頁往下捲動無法載入更多

2023-09-04 08:34 UTC, erase2004 commented on lib/pages/storyPage/news/story_widget.dart
> +          story.updatedAt,
未收到更新

2023-09-04 08:34 UTC, erase2004 commented on lib/pages/storyPage/news/story_widget.dart
> +            story.publishedDate,
未收到更新

2023-09-04 08:34 UTC, erase2004 commented on lib/blocs/storyPage/listening/cubit.dart
> +          '${Environment().config.listeningWidgetApi}youtube/search?maxResults=7&order=date&part=snippet&channelId=UCYkldEK001GxR884OZMFnRw');
尚未修正

2023-09-05 04:41 UTC, erase2004 approved these changes
相關問題皆已修正，Good work，LGTM 👏 🥳 👍 

https://github.com/mirror-media/apps-configs/pull/3#discussion_r1315347335

2023-09-05 06:57 UTC, merged