Feat(Election widget): 新增大選即時開票 Widget
mirror-media/InstantCoffee pull request #329
Opened 2023-12-22 05:30 UTC by MikeMirrorMedia

[Asana 需求卡](https://app.asana.com/0/1206085248687494/1206191166513758/f)

[App-config](https://github.com/mirror-media/apps-configs/commit/fbb27842f598e646dc4a28d907914663d0f21c71)

[Firebase Remote Config](https://console.firebase.google.com/u/1/project/mirrormediaapptest/config?hl=zh-cn) 控制是否顯示

因應此次Widget 與新聞共用，因此將此顯示Widget額外放置在Git上，由兩個App自行import
[RealTimeInvoiceWidget](https://github.com/mirror-media/RealTimeInvoiceWidget)

ScreenShot:
![Simulator Screenshot - iPhone 14 Pro Max - 2023-12-22 at 13 10 06](https://github.com/mirror-media/InstantCoffee/assets/139741357/87fe8f41-1a0a-4e0e-937c-8bf427918c83)

2023-12-25 08:20 UTC, erase2004 requested changes
```
/models/election/candidate.dart
/models/election/municipality.dart
/blocs/election/election_cubit.dart
/blocs/election/election_cubit.dart
/services/election_service.dart
```
 這些檔案可一併刪除或標注棄用

2023-12-25 08:22 UTC, erase2004 commented on pubspec.yaml
> +    - assets/image/election/dpp_logo.png
這些 asset file 應該不用，在 RealTimeInvoiceWidget 使用 Image.asset 的地方，搭配 packge 參數，讓它正確引用自身的 asset 即可
https://github.com/mirror-media/RealTimeInvoiceWidget/blob/4890b876be778e6c863f2fb86bb40f847090cd83/lib/real_time_invoice/widget/candidate_widget.dart#L28-L30
https://github.com/mirror-media/RealTimeInvoiceWidget/blob/4890b876be778e6c863f2fb86bb40f847090cd83/lib/real_time_invoice/widget/list_item_widget.dart#L31-L53

2023-12-25 08:38 UTC, erase2004 commented on pubspec.yaml
> +    - assets/image/election/dpp_logo.png
ref: https://api.flutter.dev/flutter/widgets/Image/Image.asset.html#widgets.Image.asset.2

2023-12-26 07:28 UTC, erase2004 reviewed
週刊 App Figma
https://www.figma.com/file/XMYBkeWSzrMc4KZ1c1U2k1/%E9%80%B1%E5%88%8AAPP-3.0?type=design&node-id=863-213&mode=design&t=8AnKnQUgp3QRkIBe-4
電視 App Figma
https://www.figma.com/file/2ZmETBLX3PObFn8I7AIb8l/MirrorTV_APP?type=design&node-id=2610-3893&mode=design&t=zzYaeuhvOAJjVZCk-4
詢問一下，週刊 App Figma 中有顯示 `全國投票率` 的資訊，但是電視的部份沒有，兩邊是統一不顯示全國投票率資訊了？

2023-12-26 07:44 UTC, MikeMirrorMedia commented
@erase2004 是的～
全國投票率已經移除
我再告知PM移除

2023-12-26 07:45 UTC, erase2004 approved these changes
LGTM 👏

2023-12-26 07:49 UTC, merged